baseURL: https://ypiolet.fr
languageCode: en-us
title: ~ypiolet
enableEmoji: true
enableGitInfo: true

# enableRobotsTXT: true
# googleAnalytics: ""

params:
  author: Youenn Piolet
  author-github: https://github.com/uZer
  footer: Copyright test

menu:
  main:
  - identifier: posts
    url: /posts/
    weight: 10
  - identifier: projects
    url: /projects/
    weight: 50
  - identifier: knowledge
    url: /data/
    weight: 80
  # - identifier: logs
  #   url: /logs/
  #   weight: 90
  - identifier: about
    url: /pages/about/
    weight: 100

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: solarized-dark
    tabWidth: 2
