baseURL: https://ypiolet.fr
languageCode: en-us
title: ~ypiolet
enableEmoji: false
enableGitInfo: true

# enableRobotsTXT: true
# googleAnalytics: ""

params:
  author: Youenn Piolet
  repo: https://github.com/uZer/ypiolet.fr
  socials:
    code:
      github: uZer
    creative:
      bandcamp: schematicwizard
      instagram: schematicwizard
      myspace93: 1040
      pinterest: schematicwizard
      soundcloud: schematic-wizard
      spotify: _u.zer_
      youtube: UCjKT4F2xTNyXIAFdFlUVEaQ
    intercom:
      facebook: schematicwizard
      linktree: schematicwizard
      mastodon: "merveilles.town/@schematicwizard"
      twitter: schematicwizard
    misc:
      lastfm: Psyco-uZer
      steam: schematicwizard
    pro:
      linkedin: ypiolet
  socialurls:
    bandcamp: "https://VALUE.bandcamp.com"
    facebook: "https://facebook.com/VALUE"
    github: "https://github.com/VALUE"
    instagram: "https://instagram.com/VALUE"
    lastfm: "https://www.last.fm/user/VALUE"
    linkedin: "https://linkedin.com/in/VALUE"
    linktree: "https://linktr.ee/VALUE"
    mastodon: "https://VALUE"
    myspace93: "https://myspace.windows93.net/index.php?id=VALUE"
    pinterest: "https://pinterest.com/VALUE"
    soundcloud: "https://soundcloud.com/VALUE"
    spotify: "https://open.spotify.com/user/VALUE"
    steam: "https://steamcommunity.com/id/VALUE"
    twitter: "https://twitter.com/VALUE"
    youtube: "https://youtube.com/channel/VALUE"

menu:
  main:
  - identifier: posts
    url: /posts/
    weight: 10
  - identifier: projects
    url: /projects/
    weight: 50
  - identifier: knowledge
    url: /data/
    weight: 80
  # - identifier: logs
  #   url: /logs/
  #   weight: 90
  - identifier: about
    url: /pages/about/
    weight: 100

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: solarized-dark
    tabWidth: 2

